let openingList;
let badChessBoard = '[[{"code":"rd","team":false,"piece":"r","moves":0,"clicked":false,"lastMoveNum":-10},"NA",{"code":"bd","team":false,"piece":"b","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"qd","team":false,"piece":"q","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"kd","team":false,"piece":"k","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"bd","team":false,"piece":"b","moves":0,"clicked":false,"lastMoveNum":-10},"NA",{"code":"rd","team":false,"piece":"r","moves":0,"clicked":false,"lastMoveNum":-10}],[{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},"NA","NA",{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pd","team":false,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10}],["NA","NA",{"code":"pd","team":false,"piece":"p","moves":1,"clicked":false,"lastMoveNum":7},"NA","NA",{"code":"nd","team":false,"piece":"n","moves":1,"clicked":false,"lastMoveNum":3},"NA","NA"],["NA","NA","NA","NA","NA","NA","NA","NA"],["NA","NA","NA","NA",{"code":"pl","team":true,"piece":"p","moves":1,"clicked":false,"lastMoveNum":0},"NA","NA","NA"],["NA","NA","NA","NA","NA","NA","NA","NA"],[{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},"NA",{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"pl","team":true,"piece":"p","moves":0,"clicked":false,"lastMoveNum":-10}],[{"code":"rl","team":true,"piece":"r","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"nl","team":true,"piece":"n","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"bl","team":true,"piece":"b","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"ql","team":true,"piece":"q","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"kl","team":true,"piece":"k","moves":0,"clicked":false,"lastMoveNum":-10},{"code":"bl","team":true,"piece":"b","moves":0,"clicked":false,"lastMoveNum":-10},"NA",{"code":"rl","team":true,"piece":"r","moves":0,"clicked":false,"lastMoveNum":-10}]]'
$.getJSON("/resources/json/openings.json", function(result) {
    openingList = result
});
let pgnTestVal = '[Event "?"]\n' +
    '[Site "chess.oggyp.com"]\n' +
    '[Date "2021.8.24"]\n' +
    '[Round "?"]\n' +
    '[White "OggyPrit"]\n' +
    '[Black "OggyP"]\n' +
    '[Result "1-0"]\n' +
    '\n' +
    '1. e3 e6 2. Bd3 Qf6 3. Nf3 Nc6 4. O-O b6 5. Qe2 Ba6 6. Ng5 O-O-O 7. e4 h6 8. Bxa6+ Kb8 9. Qd3 Ne5 10. Qd5 Ng4 11. Qb7# 1-0'